# -*- coding: utf-8 -*-
"""MediosElectricos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wo0fNadh5TbkbSBuprrSpZb7ONxA2gBZ
"""

import numpy as np 
import matplotlib.pyplot as plt

alpha = 0.000001 #@param {type: "slider", min: 0, max: 0.000002, step: 0.0000001}
f = 1e3 
T = 1/f 
v = 3e8 
tand= 0.20e-3
er = 2.6 
e0 = 8.85e-12 
e = er*e0
ur = 1 
u0 = 4e-12*np.pi
u = ur*u0
lambdaa = v/f 
w = 2*np.pi*f
sigma= tand * w * e
#beta = (2*np.pi)/lambd
beta = w*np.sqrt(u*e)
if (alpha!=0): delta = 1/alpha 
else: delta=0
z = np.arange(0,1000000,100) 
envolvente = np.exp(-alpha*z) 
cs = np.cos(beta*z)
Ez = envolvente*cs 


rectangulo = plt.Rectangle((0,-1.2),delta,2.4,color='#77F2D4',alpha=.3)

fig, ax = plt.subplots(1,2,figsize=(18,6))
ax[0].axis([0,z[-1],-1.2,1.2])
ax[0].plot(z,envolvente, 'b-.',label = 'envolvente')
ax[0].plot(z, cs, label='Coseno',color='#FF0000',lw=2)
ax[0].set_xlabel('Distancia z (m)', fontsize=14)
ax[0].set_ylabel('E [V/m]', fontsize=14)
ax[0].legend(loc='lower right')

ax[1].axis([0, z[-1], -1.2, 1.2])
ax[1].add_artist(rectangulo)
ax[1].plot(z, envolvente, 'b-.',label='Envolvente')
ax[1].plot(z, Ez, label='Campo eléctrico', lw=3,color='#FF0000')
ax[1].set_xlabel('Distancia z (m)', fontsize=14)
ax[1].legend(loc='lower right')

fig.show()

import numpy as np
import matplotlib.pyplot as plt

f = 1e3
er = 1
ur = 1
sigma = 5.8e7
alpha = np.sqrt(np.pi*er*ur*f)
beta = np.sqrt(np.pi*er*ur*f)
delta= 500000
w = 2*np.pi*f
z = np.arange(0,.2,.001)
envolvente = np.exp(-alpha*z) 
cs = np.cos(beta*z)
Ez = envolvente*cs


rectangulo = plt.Rectangle((0,-1.2),delta,2.4,color='#77F2D4',alpha=.3)

fig, ax = plt.subplots(1,2,figsize=(18,6))
ax[0].axis([0,z[-1],-1.2,1.2])
ax[0].plot(z,envolvente, 'b-.',label = 'envolvente')
ax[0].plot(z, cs, label='Coseno',color='#FF0000',lw=3)
ax[0].set_xlabel('Distancia z (m)', fontsize=14)
ax[0].set_ylabel('E [V/m]', fontsize=14)
ax[0].legend(loc='lower right')


ax[1].axis([0, z[-1], -1.2, 1.2])
ax[1].add_artist(rectangulo)
ax[1].plot(z, envolvente, 'b-.',label='Envolvente')
ax[1].plot([0, z[-1]], [0.37, 0.37], 'k--', lw=1, label='0.37')
ax[1].plot(z, Ez, label='Campo eléctrico', lw=3,color='#FF0000')
ax[1].set_xlabel('Distancia z (m)', fontsize=14)
ax[1].legend(loc='lower right')

fig.show()

import numpy as np
import matplotlib.pyplot as plt

Frecuencia_PHz = 10001  #@param {type: "slider", min: 1, max: 10001, step: 1000}

f = Frecuencia_PHz*1e15;
e0 = 8.8542e-12;
u0 = 1.2566e-6;
er = 1;
ur = 1;
sigma = 5.8e7;

omega = 2*np.pi*f;
e = e0*er;
u = u0*ur;
tand = sigma/(omega*e);
alpha = omega*np.sqrt(u*e/2)*np.sqrt(np.sqrt(1+tand*2)-1);
beta  = omega*np.sqrt(u*e/2)*np.sqrt(np.sqrt(1+tand*2)+1);
delta = 1/alpha
lambd = 2*np.pi/beta

z = np.arange(0,u, e*1e-1)
Env = np.exp(-alpha*z)
senal = Env*np.cos(-beta*z)

f, ax = plt.subplots( figsize=(12, 6))

rec_r = plt.Rectangle((0, -1.2), 3, 2.4, color='#fff616', alpha = 0.3)
rec_b = plt.Rectangle((delta/lambd, -1.2), 3-delta/lambd, 2.4, color='#bfffb1')

ax.add_artist(rec_r)
ax.add_artist(rec_b)
ax.plot(z/lambd, senal,color = '#0c009a', label='E',lw=2)
ax.plot(z/lambd, Env,'k--',label='Envolvente',lw=2)
ax.plot([0, 3], [0.37, 0.37], 'r--', lw=2, label='0.37')
ax.axis([0, 3, -1.2, 1.2])
ax.grid(color = 'k', alpha = 0.3)
ax.set_xlabel('Longitud z', fontsize=14)
ax.set_ylabel('E (V/m)', fontsize=14)